laravel/routes/web.php
<?php

use App\Http\Controllers\ContrateController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ServicosController;
use App\Models\Servico;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('en/services/{slug}', [ServicosController::class, 'index'])->name('servicos-en');
Route::get('es/servicios/{slug}', [ServicosController::class, 'index'])->name('servicos-es');
Route::get('servicos/{slug}', [ServicosController::class, 'index'])->name('servicos');

Route::post('servicos/mais-informacoes', [ServicosController::class, 'formPost'])->name('servicos.post');

Route::get('en/hire', [ContrateController::class, 'index'])->name('contrate-en');
Route::get('es/contratar', [ContrateController::class, 'index'])->name('contrate-es');
Route::get('contrate', [ContrateController::class, 'index'])->name('contrate');

Route::post('contrate', [ContrateController::class, 'formPost'])->name('contrate.post');

Route::post('aceite-de-cookies', [HomeController::class, 'postCookies'])->name('aceite-de-cookies.post');

// LANG
Route::get('lang/{lang}', function ($lang) {
    if (in_array($lang, ['pt', 'en', 'es'])) {
        Session::put('locale', $lang);
    }
    return back();
})->name('lang');

require __DIR__ . '/auth.php';

laravel/app/Models/Contato.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Contato extends Model
{
    use HasFactory;
    use Notifiable;

    protected $table = 'contatos';

    protected $guarded = ['id'];
}

laravel/app/Models/ContrateConosco.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContrateConosco extends Model
{
    use HasFactory;

    protected $table = 'contrate_conosco';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/Painel/ContatosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatosRequest;
use App\Models\Contato;
use Illuminate\Http\Request;

class ContatosController extends Controller
{


    public function index()
    {
        $registro = Contato::first();

        return view('painel.contatos.edit', compact('registro'));
    }

    public function update(ContatosRequest $request, $registro)
    {
        try {
            $registro = Contato::where('id', $registro)->first();

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('contatos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/contatos/mais-informacoes/index.blade.php
@extends('painel.layout.template')

@section('content')

@include('painel.layout.flash')

<legend class="mb-4">
    <h2 class="m-0">SERVIÇOS - MAIS INFORMAÇÕES

      {{--   <a ahref='#' class='btn btn-primary w-25'>Extrair Contatos Excel/.CSV</a> --}}

    </h2>
</legend>

@if(!count($contatos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else



<a href='https://edcservicos.com.br/a_export/export.php' class='btn btn-info my-2'><i class="fa-solid fa-file-csv fa-2x"></i> Exportar Cotatos: .CSV / .XLS</a>




<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="servicos_mais_infos">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Serviço</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Empresa</th>
                <th scope="col">Cargo</th>
                <th class="no-filter" scope="col"><i class="bi bi-gear-fill me-2"></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($contatos as $contato)
            <tr class="@if(!$contato->lido)alert alert-warning @endif" id="{{ $contato->id }}">
                <td data-order="{{ $contato->created_at_order }}">{{ $contato->created_at }}</td>
                <td>{{ $contato->servico }}</td>
                <td>{{ $contato->nome }}</td>
                <td class="d-flex flex-row align-items-center">
                    <button class="btn btn-dark btn-sm clipboard me-2" data-clipboard-text="{{ $contato->email }}">
                        <i class="bi bi-clipboard"></i>
                    </button>
                    {{ $contato->email }}
                </td>

                <td>{{$contato->empresa}}</td>
                <td>{{$contato->cargo}}</td>

                <td class="crud-actions">

                   

                    {!! Form::open([
                    'route' => ['mais-informacoes.destroy', $contato->id],
                    'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm" role="group">
                        <a href="{{ route('mais-informacoes.show', $contato->id ) }}" class="btn btn-primary btn-sm">
                            <i class="bi bi-chat-text-fill me-2"></i>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="bi bi-trash-fill me-2"></i>Excluir</button>

                        <a href="{{ route('mais-informacoes.toggle', $contato->id) }}" class="btn btn-sm {{ ($contato->lido ? 'btn-warning' : 'btn-success') }}">
                            @if($contato->lido)
                            <i class="bi bi-arrow-repeat"></i>
                            @else
                            <i class="bi bi-check2-circle"></i>
                            @endif
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endif

@endsection

laravel/resources/views/painel/contatos/mais-informacoes/show.blade.php
@extends('painel.layout.template')

@section('content')

<legend class="mb-4">
    <h2 class="m-0">SERVIÇOS - MAIS INFORMAÇÕES</h2>
</legend>

<div class="mb-3 col-12">
    <label>Data</label>
    <div class="well">{{ $contatoServicos->created_at }}</div>
</div>

<div class="mb-3 col-12">
    <label>Serviço</label>
    <div class="well">{{ $contatoServicos->servico }}</div>
</div>

<div class="mb-3 col-12">
    <label>Nome</label>
    <div class="well">{{ $contatoServicos->nome }}</div>
</div>

<div class="mb-3 col-12">
    <label>E-mail</label>
    <div class="well">
        <button class="btn btn-dark btn-sm clipboard me-2" data-clipboard-text="{{ $contatoServicos->email }}">
        <i class="bi bi-clipboard"></i>
        </button>
        {{ $contatoServicos->email }}
    </div>
</div>

@if($contatoServicos->telefone)
<div class="mb-3 col-12">
    <label>Telefone</label>
    <div class="well">{{ $contatoServicos->telefone }}</div>
</div>
@endif

<div class="mb-3 col-12">
    <label>Mensagem</label>
    <div class="well-msg">{!! $contatoServicos->mensagem !!}</div>
</div>


<div class="d-flex align-items-center mt-4">
    <a href="{{ route('mais-informacoes.index') }}" class="btn btn-secondary btn-voltar">Voltar</a>
</div>

@stop